//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallpaperChanger.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PictureLinkResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PictureLinkResource() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WallpaperChanger.Resources.PictureLinkResource", typeof(PictureLinkResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu https://timedotcom.files.wordpress.com/2015/01/455084116.jpg.
        /// </summary>
        internal static string Bieber1 {
            get {
                return ResourceManager.GetString("Bieber1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu https://i.ytimg.com/vi/KkqLDvSRnA4/maxresdefault.jpg.
        /// </summary>
        internal static string Gej1 {
            get {
                return ResourceManager.GetString("Gej1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu http://www.newsweek.pl/g/i.aspx/0/0/newsweek/635806139741402395.jpg.
        /// </summary>
        internal static string Gej2 {
            get {
                return ResourceManager.GetString("Gej2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu http://www.vijesti.me/media/cache/58/0a/580a62047251dc232fafdc2c7a06f69e.jpg.
        /// </summary>
        internal static string Gej3 {
            get {
                return ResourceManager.GetString("Gej3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu https://icdn.2cda.pl/g/49266_ca5f9b64df5ba2bb0d42837ffa33a3ee.jpeg.
        /// </summary>
        internal static string karny1 {
            get {
                return ResourceManager.GetString("karny1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu https://www.rowerynajtaniej.pl/userdata/gfx/45ec28ca0cfe887cfa95866996f6f8de.jpg.
        /// </summary>
        internal static string Pedal1 {
            get {
                return ResourceManager.GetString("Pedal1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu https://cont7.naekranie.pl/wp-content/uploads/2017/06/My-Little-Pony-1.jpg.
        /// </summary>
        internal static string Pony1 {
            get {
                return ResourceManager.GetString("Pony1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu https://www.tapeciarnia.pl/tapety/normalne/152591_my_little_pony_przyjazn_to_magia_kucyki.jpg.
        /// </summary>
        internal static string Pony2 {
            get {
                return ResourceManager.GetString("Pony2", resourceCulture);
            }
        }
    }
}
